liip_imagine:
    filter_sets:
        thumbnail:
            quality: 75
            filters:
                thumbnail:
                    size: [360, 230]
                    mode: outbound
        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [800, 530]
                    mode: outbound
                background:
                    size: [800, 530]
                    position: center
                    color: '#e9ecef'
                watermark:
                    image: '../public/images/watermark.png'
                    size: 0.2
                    position: bottomright